version: "3.7"
services:
  db:
    image: mysql:5.7
    command: mysqld --sql_mode=""
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - /home/vinicius/www/mysql/mysql-data:/var/lib/mysql
      - /home/vinicius/www/mysql/mysql-conf:/etc/mysql/conf.d
      - /home/vinicius/www/mysql/shared:/shared
    networks:
      - edelivery_network
    ports: 
      - "3306:3306"

networks:
  edelivery_network:
    external: true
